name: Build macOS
run-name: Build macOS
on: 
  push

jobs:
  Build-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - run: |
          pip install -r requirements.txt
          pip install pyinstaller
          python3 helper_scripts/package_mac.py
          mkdir -p src/dist/Qtcord-macOS
          mv src/dist/Qtcord-macOS.app src/dist/Qtcord-macOS

      - uses: actions/upload-artifact@v4
        with:
          name: "Qtcord-macOS"
          path: "src/dist/Qtcord-macOS"
